import 'package:hive/hive.dart';
import 'category.dart';

// Tells Hive this class can be stored — typeId must be unique across all models
part 'transaction.g.dart';

@HiveType(typeId: 0)
class Transaction extends HiveObject {
  @HiveField(0)
  final String id;
  // ↑ Unique identifier generated by the uuid package

  @HiveField(1)
  final double amount;
  // ↑ Amount in Ariary (e.g. 5000.0)

  @HiveField(2)
  final String type;
  // ↑ Either "income" or "expense"

  @HiveField(3)
  final String category;
  // ↑ Stored as a String (e.g. "food") — converted using CategoryExtension

  @HiveField(4)
  final DateTime date;
  // ↑ Date and time of the transaction

  @HiveField(5)
  final String? note;
  // ↑ Optional description (e.g. "Lunch at Shoprite")

  @HiveField(6)
  final bool aiCategorized;
  // ↑ True if the category was detected by Gemini AI

  Transaction({
    required this.id,
    required this.amount,
    required this.type,
    required this.category,
    required this.date,
    this.note,
    this.aiCategorized = false,
  });

  // Returns true if this is an expense
  bool get isExpense => type == 'expense';

  // Returns true if this is an income
  bool get isIncome => type == 'income';

  // Returns the Category enum from the stored string
  Category get categoryEnum => CategoryExtension.fromString(category);

  // Creates a copy of this transaction with updated fields
  Transaction copyWith({
    String? id,
    double? amount,
    String? type,
    String? category,
    DateTime? date,
    String? note,
    bool? aiCategorized,
  }) {
    return Transaction(
      id: id ?? this.id,
      amount: amount ?? this.amount,
      type: type ?? this.type,
      category: category ?? this.category,
      date: date ?? this.date,
      note: note ?? this.note,
      aiCategorized: aiCategorized ?? this.aiCategorized,
    );
  }
}
