import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'models/transaction.dart';
import 'models/budget.dart';
import 'providers/transaction_provider.dart';
import 'providers/budget_provider.dart';
import 'providers/theme_provider.dart';
import 'router/app_router.dart';

void main() async {
  // ↑ "async" because we need to await several initializations
  //   before launching the app

  // Ensures Flutter is ready before running async code
  WidgetsFlutterBinding.ensureInitialized();

  // Load the .env file to access the Gemini API key
  await dotenv.load(fileName: '.env');

  // Initialize Hive in the correct folder on the device
  await Hive.initFlutter();

  // Register the Hive adapters generated by build_runner
  // ↑ Without this, Hive doesn't know how to read/write
  //   your Transaction and Budget objects
  Hive.registerAdapter(TransactionAdapter());
  Hive.registerAdapter(BudgetAdapter());

  // Open the Hive boxes (like opening database tables)
  await Hive.openBox<Transaction>('transactions');
  await Hive.openBox<Budget>('budgets');

  // Launch the app
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      // ↑ MultiProvider lets us register multiple providers at once.
      //   Think of it as Pinia's createPinia() — it makes all stores
      //   available everywhere in the app.
      providers: [
        ChangeNotifierProvider(
          create: (_) => ThemeProvider()..init(),
          // ↑ ".." is the cascade operator — calls init() on the
          //   same object that was just created. Equivalent to:
          //   final p = ThemeProvider(); p.init(); return p;
        ),
        ChangeNotifierProvider(
          create: (_) => TransactionProvider()..init(),
        ),
        ChangeNotifierProvider(
          create: (_) => BudgetProvider()..init(),
        ),
      ],
      child: Consumer<ThemeProvider>(
        // ↑ Consumer listens to ThemeProvider and rebuilds
        //   MaterialApp whenever the theme changes.
        //   Like a computed() that wraps the whole app in Pinia.
        builder: (context, themeProvider, child) {
          return MaterialApp.router(
            // ↑ ".router" variant tells Flutter we're using
            //   go_router for navigation instead of the
            //   classic Navigator.

            title: 'Finance Tracker',

            debugShowCheckedModeBanner: false,
            // ↑ Removes the red "DEBUG" banner on the top right

            // Light theme configuration
            theme: ThemeData(
              colorScheme: ColorScheme.fromSeed(
                seedColor: const Color(0xFF1D9E75),
                // ↑ Our main teal color — Flutter derives
                //   the full color palette from this seed
              ),
              useMaterial3: true,
              // ↑ Enables Material Design 3 (latest version)
            ),

            // Dark theme configuration
            darkTheme: ThemeData(
              colorScheme: ColorScheme.fromSeed(
                seedColor: const Color(0xFF1D9E75),
                brightness: Brightness.dark,
                // ↑ Same seed color but Flutter adapts it
                //   for dark backgrounds automatically
              ),
              useMaterial3: true,
            ),

            // Which theme to use — controlled by ThemeProvider
            themeMode: themeProvider.themeMode,

            // The router that handles all navigation
            routerConfig: AppRouter.router,
          );
        },
      ),
    );
  }
}
